### ISSUE TITLE
App crashes on first start

### ISSUE THREAD

**Issue by Geekgasm** [Geekgasm/kintrol#6]
When running on a new device where no previous configuration was stored, the app crashes on startup with the following exception:

```
07-26 10:48:43.445    1453-1453/eu.geekgasm.kintrol E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.geekgasm.kintrol/eu.geekgasm.kintrol.DeviceChooserActivity}: java.lang.NullPointerException: storage == null
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException: storage == null
            at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
            at java.util.Arrays.asList(Arrays.java:154)
            at eu.geekgasm.kintrol.DeviceInfoPersistenceHandler.loadDeviceList(DeviceInfoPersistenceHandler.java:42)
            at eu.geekgasm.kintrol.DeviceChooserActivity.onCreate(DeviceChooserActivity.java:50)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

Observed with version 0.6

**Comment by Geekgasm** [comment]
Fixed with commit https://github.com/Geekgasm/kintrol/commit/a680ba3337db254759b89cf6e399c2dc1805e910
Released with version 0.7: https://github.com/Geekgasm/kintrol/releases/tag/0.7
